name: update the readme!!

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  SLACK_ID: "U05MKEZUY67"
  GITHUB_USERNAME: "espcaa"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: clone the repo
        uses: actions/checkout@v6

      - name: download gooo :)
        uses: actions/setup-go@v6
        with:
          go-version: "1.21"

      - name: install the shiny packages
        run: cd scripts && go mod tidy && go install

      - name: running the script...
        run: cd scripts && go run update-readme.go

      - name: committing!
        run: |
          git config --global user.name "bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "daily readme update" || echo "No changes to commit"
          git push
